baseURL = "https://taguchiyuma.github.io/web"
relativeURLs = true
canonifyurl = true
publishDir = "docs"
theme = "mytheme-personal"
hasCJKLanguage = true
summaryLength = 140
DefaultContentLanguage = "ja"
DefaultContentLanguageInSubdir = false

[taxonomies]
    tag = "tags"
    category = "categories"

[permalinks]
    posts = "/posts/:year:month:day/"

[languages]
    [languages.ja]
        #baseURL = ""
        weight = 1
        title = "Yuma Taguchi"
    [languages.en]
        #baseURL = "en/"
        weight = 1
        title = "Yuma Taguchi"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true